### ISSUE TITLE
Fail to run example on Apple Silicon M1 with Rust version 1.66

### ISSUE THREAD

**Issue by shaodan** [nacos-group/nacos-sdk-rust#92]
```
  = note: ld: warning: directory not found for option '-L/Users/mac/workspace/opensource/nacos-sdk-rust/target/debug/build/libz-sys-1fdb361784ca5052/out/build'
          Undefined symbols for architecture arm64:
            "_res_9_getservers", referenced from:
                _init_by_resolv_conf in libgrpcio_sys-63fbe17b71987d12.rlib(ares_init.c.o)
            "_res_9_ndestroy", referenced from:
                _init_by_resolv_conf in libgrpcio_sys-63fbe17b71987d12.rlib(ares_init.c.o)
            "_res_9_ninit", referenced from:
                _init_by_resolv_conf in libgrpcio_sys-63fbe17b71987d12.rlib(ares_init.c.o)
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)


warning: `nacos-sdk` (example "simple_app") generated 1 warning
```

**Comment by CherishCai** [comment]
I have the same problem in M1 Rust 1.66.1

**Comment by CherishCai** [comment]
This needs `tikv/grpc-rs` to deal with it.

**Comment by CherishCai** [comment]
At present, I only reduce the version of Rust to avoid this problem. `rustup default 1.65.0`

**Comment by CherishCai** [comment]
@shaodan It is work in M1 Rust 1.68.0 , maybe have a try.
